AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'Rakefile'

# Layout
Layout/SpaceInsideStringInterpolation:
  Enabled: false

# Metrics
Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'spec/**/*.rb'

# Style
Style/Documentation:
  Enabled: false
