AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'Rakefile'

# Layout
Layout/SpaceInsideStringInterpolation:
  Enabled: false

# Metrics
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Max: 180

Metrics/MethodLength:
  Max: 35

# Style
Style/Documentation:
  Enabled: false
