AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'Rakefile'

# Layout
Layout/SpaceInsideStringInterpolation:
  Enabled: false

# Style
Style/Documentation:
  Enabled: false
