default: &default
  adapter: sqlite
  user: user
  password: password
  host: localhost
  port: 5432

development:
  <<: *default
  database: db/development.db

test:
  <<: *default
  database: db/test.db

production:
  <<: *default
  database: db/production.db
